---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  environment:
    - ENVIRONMENT: production
    - TYPEORM_CONNECTION: postgres  
    - TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity{.ts,.js}
    - TYPEORM_HOST: database-1.crxy0cbhkjib.us-east-1.rds.amazonaws.com
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: postgres
    - TYPEORM_PASSWORD: mypassword
    - TYPEORM_DATABASE: udapeople
    #- TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    #- TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"

  roles:
    # Your code here
    - configure-server
    
