Description: >
    Daniel Teixeira / Infra as a code
    This template deploys an autoscaling group with four Apaches server, a loadbalancer to be in front of app´s server 
    and S3 bucket to archive App´s files.
Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        default: veeam-CPAD   
Resources:
  S3AccessEC2:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: s3bucketbackupcpad
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true   
Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket  