version: 2.1
jobs:
  deploy_Network:
   docker:
     - image: amazon/aws-cli
      # Docker image here that supports AWS CLI
   steps:
     - checkout
     - run:
        name: Create Network Infrastrucuture
        command: |
            aws cloudformation deploy \
              --template-file ./network.yml \
              --tags project=veeam-backup \
              --region us-east-1 \
              --stack-name "veeam-backup-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
  deploy_s3:
   docker:
     - image: amazon/aws-cli
      # Docker image here that supports AWS CLI
   steps:
     - checkout
     - run:
        name: Create Network Infrastrucuture
        command: |
            aws cloudformation deploy \
              --template-file ./S3.yml \
              --tags project=veeam-backup \
              --region us-east-1 \
              --stack-name "veeam-backup-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"            
workflows:
 default:
  jobs:
    - deploy_Network
    - deploy_s3     
           
    
                                                                                                                                                                                                                                                               
